setwd("/exports/eddie/scratch/nbestard/TK_scRNAseq")
library(here)
renv::load(here())
rmarkdown::render(here("rmarkdown", "import.Rmd"))
rmarkdown::render(here("rmarkdown", "QC_01.Rmd"))
rmarkdown::render(here("rmarkdown", "normalise.Rmd"))
source(here("src","R", "correct_metadata.R"))
rmarkdown::render(here("rmarkdown", "feature_select_and_batch_correct.Rmd"))
rmarkdown::render(here("rmarkdown", "clustering_01.Rmd"))
mrkdown::render("rmarkdown/analyse_up_to_clustering_with_Seurat.Rmd")
markdown::render("rmarkdown/analyse_up_to_clustering_with_Liger.Rmd")
source(here("src", "R", "combine_integrations.R"))
rmarkdown::render(here("rmarkdown", "transfer_label.R"))